### ISSUE TITLE
Compile warning after last core update. 

### ISSUE THREAD

**Issue by Nemepy** [azerothcore/mod-duel-reset#2]
Warnings in complilation after core last update.
/home/wow/azerothcore/modules/mod-premium/src/premium.cpp:120:10: warning: 'OnGossipSelect' overrides a member function but is not marked
      'override' [-Winconsistent-missing-override]
    void OnGossipSelect(Player* player, Item* item, uint32 /*sender*/, uint32 action)

/home/wow/azerothcore/modules/mod-premium/src/premium.cpp:311:31: warning: unused variable 'trainer' [-Wunused-variable]
                    Creature* trainer = player->SummonCreature(HMAGE, player->GetPositionX(), player->GetPositionY(), player->GetPosition...
                              ^
/home/wow/azerothcore/modules/mod-premium/src/premium.cpp:317:31: warning: unused variable 'trainer' [-Wunused-variable]
                    Creature* trainer = player->SummonCreature(APALADIN, player->GetPositionX(), player->GetPositionY(), player->GetPosit..

and many others.
sorry for my english , native language spanish

**Comment by Yehonal** [comment]
It's a premium module issue not duel reset
