### ISSUE TITLE
Suggestion: improved cooldown reset

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-duel-reset#5]
- **Improved cooldown reset**: when duel starts it resets the player cooldowns, when duel ends it restores the cooldowns that the player had before the duel

**Comment by Yehonal** [comment]
I remember that we already implemented this system. Isn't it @FrancescoBorzi ?

**Comment by Yehonal** [comment]
Ok i think it's strictly related: https://github.com/azerothcore/mod-duel-reset/issues/1

@FrancescoBorzi do you have the time to complete those 2 checkboxes? :) 

I remember you had the code and we worked on it together

**Comment by FrancescoBorzi** [comment]
yes, but to be honest that was 4 years ago and I don't remember anything

**Comment by Yehonal** [comment]
I remember that you had the code somewhere, maybe we can put it in a temporary not-compiled folder and then adapt.

Just to don't lose that great stuff

**Comment by FrancescoBorzi** [comment]
@Yehonal they should be there somewhere in TC 3.3.5:

https://github.com/TrinityCore/TrinityCore/pulls?q=is%3Apr+Duel+Reset+is%3Aclosed

I've implemented this feature together with @GigaDev90 back then

**Comment by Yehonal** [comment]
LOL they have the duel reset inside the core xD

Ok, then the source is there...at least we can easily import it asap. Good reminder. Thank you :)

**Comment by FrancescoBorzi** [comment]
> LOL they have the duel reset inside the core xD

happens when you don't have Yehonal and his module system so I had no alternatives :)
