### ISSUE TITLE
mod-duel-reset DC in all players

### ISSUE THREAD

**Issue by shuradumau** [azerothcore/mod-duel-reset#8]
I am reporting a problem that is occurring when you have the cd reset module on the server.

the problem is this, when it resets the DC server several times in all logged in accounts, there players need to log in again, this only occurs when you have multiple accounts logged in.

module: https://github.com/azerothcore/mod-duel-reset

Azerothcore rev. fa9638a1b1f+ 2019-05-29 Master (branch ) (win64, Release)

**Comment by milestorme** [comment]
Am using this module and have no issues with it cannot reproduce, please make sure you remove any core modifications before testing as this module works on latest revision

**Comment by BarbzYHOOL** [comment]
give more details on how to reproduce
